spring:
  application:
    name: cloudapp-microservice-springcloud-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

server:
  port: 20001

alicloud:
  deployment:
    mode: EDAS_MANAGED